services:
    # This service is necessary to make the ParamConverter available for MongoDB documents
    doctrine_mongo_db_param_converter:
        class: 'Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter'
        arguments: ['@doctrine_mongodb']
        tags:
            - { name: 'request.param_converter', converter: 'doctrine.odm' }

    app.gpx.segment_merger_transformer:
        class: 'RandoNavigo\Gpx\SegmentMergerTransformer'
