services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/RandoNavigo available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    RandoNavigo\:
        resource: '../../src/RandoNavigo/*'
        exclude: '../../src/RandoNavigo/{Document,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # This service is necessary to make the ParamConverter available for MongoDB documents
    doctrine_mongo_db_param_converter:
        class: 'Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter'
        arguments: ['@doctrine_mongodb']
        tags:
            - { name: 'request.param_converter', converter: 'doctrine.odm' }
