version: '3'
services:
  yarn:
    build: docker/web
    working_dir: /var/www/randonavigo
    volumes:
      - ./app:/var/www/randonavigo

  php:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Paris
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/randonavigo
    working_dir: /var/www/randonavigo

  webserver:
    image: nginx:1.16-alpine
    depends_on:
      - php
    volumes:
      - ./app:/var/www/randonavigo
      - ./docker/nginx/randonavigo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8082:80

  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
