controllers:
    resource: ../src/Controller/
    type: annotation

help_gpx:
    path: /help/gpx
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/help/gpx.html.twig

about:
    path: /a-propos
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/about.html.twig
